# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ca50f1ef73048994c5015f53abac09b030a1fc37de4792cf7c12aedfea87df6f061f46058fb1826d5a15489028f264bfb9876cec5f6e11c8025ed5868e10ba8

test:
  secret_key_base: 033108de08b219cdc1fed9449ad24f2617283dd2edaeb2a4f0ca2cbd4d4b8115789c1b330e061c1f7fb24260255196720d04e8dd677dc58c356b437582113925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
